language: android
sudo: required
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

jdk:
  - oraclejdk8
git
after_success:
 - ./gradlew clean jacocoTestReport coveralls